### ISSUE TITLE
I get an error when starting the server

### ISSUE THREAD

**Issue by NotWorkingCode** [BrettMayson/Arma3Server#73]
I created a scenario in which I placed the player and Zeus. But when I run this script, I get an error:

`Warning Message: You cannot play/edit this mission; it is dependent on downloadable content that has been deleted.\na3_characters_f`

In this case, the server is not displayed in the list of servers

My docker-compose.yml:

```
version: '3.8'

services:

  arma-server:
    image: ghcr.io/brettmayson/arma3server/arma3server:latest
    container_name: arma-server
    platform: linux/amd64
    env_file: .env
    ports:
      - 2302-2306/udp
    volumes:
      - './data/missions:/arma3/mpmissions'
      - './data/configs:/arma3/configs'
      - './data/mods:/arma3/mods'
      - './data/servermods:/arma3/servermods'
    restart: unless-stopped
    depends_on:
      - arma-ftp
      - arma-database

  arma-ftp:
    image: garethflowers/ftp-server
    container_name: arma-ftp
    environment:
      - FTP_PASS=***
	  - FTP_USER=***
    ports:
      - '20-21:20-21/tcp'
      - '40000-40009:40000-40009/tcp'
    volumes:
      - './data:/home/***'
    restart: unless-stopped

  arma-database:
    image: mariadb:10.11
    container_name: arma-database
    environment:
      - MYSQL_ROOT_PASSWORD=***
      - MYSQL_DATABASE=***
    volumes:
      - './data/database:/var/lib/mysql'
```
